### PR TITLE
CNAB Core 1.0 GA

### PR DESCRIPTION
**Pull request by technosophos**
This commit marks the Working Group Acceptance (GA) of the CNAB Core 1.0 specification.

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

### CODE REVIEW

**Comment by technosophos** [comment]
The following people MUST LGTM this PR before it is merged:

@radu-matei
@simonferquel
@technosophos
@youreddy
@jeremyrickard

**Comment by technosophos** [comment]
According to the guidelines, we actually only need a 2/3 majority, not unanimity. So at 4 👍 it is considered "passed"

**Comment by youreddy** [comment]
Approved!

**Comment by squillace** [comment]
Congrats. Seriously. Hard work.

**Pull request merged**
