### PR TITLE
Update the structure of "parameters" to introduce a "fields" property

### PR DESCRIPTION
**Pull request by jeremyrickard**
Fixes: #187

This PR introduces a "fields" property to the parameters definition. Where things were previously defined under "parameters", and parallel to the "required" property, they now live under "fields".

### CODE REVIEW

**Comment by jeremyrickard** [comment]
cc: @ryanmoran

**Comment by ryanmoran** [comment]
@jeremyrickard thanks for pushing this forward as I was out of town last week. Should I wait for this to land before submitting a second PR to move JSONSchema definitions to a common `definitions` field?

**Comment by jeremyrickard** [comment]
@ryanmoran I just merged, so have at it. I’m going to add outputs soon, so I’ll wait for yours to land for thst.

**Comment by jeremyrickard** [comment]
Ha @ryanmoran I meant I’m going to do this in duffle, so I’ll wait for your change here. In general I favor small, scoped changes so feel free to PR your change

**Pull request merged**
